/Users/daehwan/Desktop/aws-prac/bbichul-back-test/venv/bin/python: can't open file '/Users/daehwan/Desktop/aws-prac/bbichul-back-test/app.py': [Errno 2] No such file or directory
 * Serving Flask app 'application' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "/Users/daehwan/Desktop/aws-prac/bbichul-back-test/application.py", line 37, in <module>
    application.run()
  File "/Users/daehwan/Desktop/aws-prac/bbichul-back-test/venv/lib/python3.9/site-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/daehwan/Desktop/aws-prac/bbichul-back-test/venv/lib/python3.9/site-packages/werkzeug/serving.py", line 984, in run_simple
    s.bind(server_address)
OSError: [Errno 48] Address already in use
